config/routes.rb
Rails.application.routes.draw do
  get 'blags/index'
  get 'blags/show'
  get 'blags/new'
  get 'blags/create'
  get 'blags/edit'
  get 'blags/update'
  get 'blags/destroy'
  root 'articles#index'

  resources :articles
  resources :blags
  resources :users
  get '/users/create', to: 'users#create', as: 'usercrea'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blag.rb
class Blag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/blags_controller.rb
class BlagsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    User.create(params["gossip_text"])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blags_helper.rb
module BlagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">

        <script type="text/javascript" src="jquery-4.4.0.js"></script>


        <title>Fangorn</title>
        <link rel="icon" type="image/x-icon" href="/Users/aimery/Desktop/THP/J5/good/assets/img/Iconsmind-Outline-Tree-22.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->

        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="app/assets/stylesheets/application.scss" rel="stylesheet" />


    </head>



    <body id="page-top">



        <!-- Navigation-->
        <nav class="navbar-fixed-top navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#about">À propos</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#projects">Articles</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!--PERSONAL SCRIPT JavaScript-->
        <script type="text/javascript">
            $(function () {
                $(document).scroll(function () {
                    var $nav = $(".navbar-fixed-top");
                $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
        });

        </script>

        <!-- Masthead-->
        <header class="masthead">

            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    <h1 class="mx-auto my-0 text-uppercase">fangorn</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Quelle forêt dans une France à +2° ?</h2>
                    <a class="btn btn-primary js-scroll-trigger" href="#about">Découvrir</a>
        


                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">Pour une nouvelle alliance avec le bois !</h2>
                        <p class="text-white-50">
                            Les arbres sont de véritables alliées pour lutter contre le réchauffement climatique,
                            doper l'agriculture en refertilisant les sols, relancer la biodiversité, purifier l'air ou même fournir un matériau du futur. Le temps d'une nouvelle alliance avec eux est venu !
                        </p>
                    </div>
                </div>
                <%= link_to image_tag("niko-photos-tGTVxeOr_Rs-unsplash-removebg-preview.png"), root_path %>
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">

                <!-- Project One Row-->
                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><img class="img-fluid" src="../abouttree.png" alt="" /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4>
                                    <%= link_to "Objectif : 1 Milliard", "/articles/new", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Planter 1 Milliard d'hectars d'arbres permettrait de retirer les deux tiers du CO2 rejetés dans l'atmosphère par l'homme. Comment atteindre un tel objectif ?</p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row justify-content-center no-gutters">
                   <div class="col-lg-6"><img class="img-fluid" src="../aboutt.jpg" alt="" /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4>
                                    <%= link_to "Pour sauver la planète, coupons des arbres !", "/blags/new", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Plaidoyer pour une mobilisation intelligente des ressources forestières.</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project three Row-->

                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><img class="img-fluid" src="../sawing.jpg" alt="" /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4>
                                    <%= link_to "Scieries & première transformation", "/articles/show", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Déclin des scieries francaises : l'arbre qui cache la forêt ?</p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project four Row-->
                <div class="row justify-content-center no-gutters">
                   <div class="col-lg-6"><img class="img-fluid" src="../louis.png" alt="" /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4>
                                    <%= link_to "Louis termine ton article", "/articles/new", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Bordel de merde.</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


        </section>

        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Ne ratez pas notre prochain article ! Abonnez-vous à notre newsletter :</h2>

                        <form action= <%= usercrea_path %> method="POST" class="form-inline d-flex">
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                            <input class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" name="gossip_text" type="email" placeholder="Entrez votre adresse mail..." />
                            <button class="btn btn-primary mx-auto" type="submit">S'inscrire</button>
                        </form>

                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Adresse</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">76 rue Jouffroy d'Abbans, Paris, France</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50"><a href="aimerycayol@gmail.com">projetfangorn@gmail.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Téléphone</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">+33665488525</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container">Copyright © Fangorn</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="app/assets/javascripts/material/scripts.js"></script>
    </body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">



        <title>Athanor</title>
        <link rel="icon" type="image/x-icon" href="/Users/aimery/Desktop/THP/J5/good/assets/img/Iconsmind-Outline-Tree-22.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->

        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/stylesheets/application.scss" rel="stylesheet" />


    </head>



    <body id="page-top">



        <!-- Navigation-->
        <nav class="navbar-fixed-top navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/">À propos</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/#projects">Articles</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!--PERSONAL SCRIPT JavaScript-->
        <script type="text/javascript">
            $(function () {
                $(document).scroll(function () {
                    var $nav = $(".navbar-fixed-top");
                $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
        });

        </script>

        <!-- Masthead-->
        <header class="masthead">
            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    

                    <h2 class="text-white-50" style="font-size:40px">Objectif : 1 Milliard</h2>
                </div>
            </div>
        </header>


          <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="brouillard.jpg" alt="" /></div>
                        <div class="featured-text text-center text-lg-left">
                            <h4 class="text-black-50 mb-0">Lutte contre le CO2 : et soudain, l’espoir … </h4>
                            <hr>
                            <p> Le monde change, le temps s’accélère, l’arbre pousse. La crise écologique est en train de s’imposer mondialement avec, comme principales menaces, la déstabilisation du climat, l’effondrement de la biodiversité, l’érosion des sols, l’épuisement des ressources, la pollution, les toxiques… </p>
            
                            <p> Et pourtant un levier existe, une vieille technologie longtemps reléguée au domaine récréatif : l’arbre. </p>
                            <p>La littérature scientifique est claire : bien employés, les arbres peuvent faire disparaître une part décisive du surplus de CO2 emmagasiné dans l’atmosphère par nos combustibles fossiles. Comme le résume Nathalie de Noblet, l’une des coordinatrices du dernier rapport du GIEC, “La planète entière est en surchauffe, il faut d’urgence la mettre à l'ombre des arbres”. </p>
                            <br/>
                            <center>
                            <img
                                src="../roadtree.jpeg"
                                height="500px"
                                width="670px"
                            />
                            </center>
                            <br/>
                            <br/>

                            <h4 class="text-black-50 mb-0">La photosynthèse : donne moi ton carbon et j’en ferai de l’or.   </h4>
                            <hr>
                            <p>On l’a compris, le meilleur (et le seul) extracteur de carbone opérationnel à notre disposition est l’arbre. Ce dernier extrait du CO2 de l’atmosphère et le transforme en bois lors du fascinant mécanisme de la photosynthèse : avec comme seul apport énergétique la lumière du soleil, la chlorophylle présente dans les feuilles transforme le CO2 en glucides (CH2O) qui fournira à la plante l'énergie dont elle a besoin pour se développer (Figure 1). </p>
                            <p>C’est ainsi qu’un banal arbre de 25 m de hauteur séquestre jusqu’à 6 tonnes de carbone, ce qui est beaucoup quand on sait qu’un Terrien en émet en moyenne 1.3 tonnes par an ! </p>

                            <br/>
                            <center>
                            <img
                                src="../photosynthese.jpg"
                                height="450px"
                                width="350px"
                            />
                            <p><em>Figure 1 : Mécanismes de la photosynthese, source : http://botarela.fr</em></p>
                            </center>
                            <br/>

                            <p>Lorsque les arbres meurent, le dioxyde de carbone emmagasiné est libéré dans l’atmosphère. D’où l’importance d’utiliser massivement les arbres comme bois d'œuvre afin de stocker définitivement le carbone dans des charpentes, des meubles, des infrastructures…  </p>
                            <p>La logique est simple : plantons plus d’arbres, nous aurons moins de CO2. Mais la Terre est limitée, avons-nous l’espace suffisant pour nourrir 8 Milliards d’êtres humains et en même temps planter des arbres ? </p>
                            <br/>

                            <h4 class="text-black-50 mb-0">Où et comment planter ? La science à la rescousse ! </h4>
                            <hr>
                            <p>Une étude publiée dans la prestigieuse revue Science en 2019 a apporté un élément de réponse. Les chercheurs ont calculé que près de 0,9 milliard d'hectares de terres inutilisées dans le monde pourraient être reboisées, ce qui permettrait à terme d’absorber les deux tiers des émissions de carbone d'origine humaine, soit 205 milliards de tonnes. </p>
                            <p> «Dans nos calculs, nous avons exclu les villes ou les zones agricoles du potentiel total de restauration, étant donné que ces zones sont nécessaires au développement humain, explique Jean-François Bastin, auteur principal de l'étude. Ce point était particulièrement important pour nous. ». Ce qui signifie que cette estimation ne prend même pas en compte les arbres que l’on pourrait mettre dans les champs dans une logique d’agroforesterie.  </p>
                            <p>Ce potentiel fait de la reforestation la première arme à notre disposition contre le réchauffement climatique, à nous de la concrétiser. </p>
                            <br/>
                            <center>
                            <img
                                src="../earth.png"
                                height="300px"
                                width="700px"
                            />
                            <p><em>Figure 2 : Répartitions des zones reboisables, à l'exclusion des terres agricoles et urbanisées. </em></p>
                            </center>
                            <br/>
                            
                            <h4 class="text-black-50 mb-0">Conclusion : 1 milliard d'hectares, 8 milliards d'Hommes. </h4>
                            <hr>
                            <p>1 milliard d'hectares représentent à peu près la taille des États-Unis. Cela représente beaucoup d’espace alors que nous sommes de plus en plus nombreux sur cette planète. Alors pourquoi l’utiliser pour planter des arbres ? </p>
                            <p>Parce que planter 1 milliard d'hectares d’arbres c’est enlever les deux tiers du CO2 d’origine humaine de l’atmosphère. </p>
                            <p>Parce que planter 1 milliard d'hectares d’arbres c’est favoriser la biodiversité en offrant un abri aux pollinisateurs, aux insectes et à des millions d’oiseaux. </b>. </p>
                            <p>Parce que planter 1 milliard d'hectares d’arbres c’est améliorer le cycle de l’eau et ralentir l’érosion. </p>
                            <p>Parce que planter 1 milliard d'hectares d’arbres c’est donner à nos enfants une matière première durable, le bois, qui a le potentiel de substituer à des matériaux comme le plastique ou le ciment. </p>
                            
                            <br/>
                            <br/>
                            <br/>
                            <br/>
                            <h5 class="text-black-50 mb-0">Sources :</h5>
                                <ul>
                                    <li>https://science.sciencemag.org/content/365/6448/76
                                    <li>https://www.science-et-vie.com/nature-et-enviro/arbres-ils-peuvent-nous-sauver-51889
                                    <li>https://www.cirad.fr/actualites/toutes-les-actualites/communiques-de-presse/2019/climat-comment-les-arbres-pourraient-sauver-la-planete
                                    <li>https://www.humanite-biodiversite.fr/article/le-rapport-du-giec-d-aout-2019-conclusions-pour-la-foret-et-les-ecosystemes</li>

                
                                </ul>
                        </div>
                    </div>
                </div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/blags/create.html.erb
<h1>Blags#create</h1>
<p>Find me in app/views/blags/create.html.erb</p>

app/views/blags/destroy.html.erb
<h1>Blags#destroy</h1>
<p>Find me in app/views/blags/destroy.html.erb</p>

app/views/blags/edit.html.erb
<h1>Blags#edit</h1>
<p>Find me in app/views/blags/edit.html.erb</p>

app/views/blags/index.html.erb
<h1>Blags#index</h1>
<p>Find me in app/views/blags/index.html.erb</p>

app/views/blags/show.html.erb
<h1>Blags#show</h1>
<p>Find me in app/views/blags/show.html.erb</p>

app/views/blags/update.html.erb
<h1>Blags#update</h1>
<p>Find me in app/views/blags/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Athanor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>